### ISSUE TITLE
IDEasy removes required entries from PATH

### ISSUE THREAD

**Issue by hohwille** [devonfw/IDEasy#504]
### Expected behavior

As a IDEasy user, I want that when I setup my shell for a project that only software for that project is added to the PATH but no important entries not related to IDEasy are removed so that everything works as expected.

### Actual behavior

To demonstrate the bug, I printed the PATH with newlines instead of the path separator (colon on Windows):

```
$ echo -e ${PATH//:/\\n/}
/c/Users/hohwille/bin
/usr/local/bin
/usr/bin
/bin
/opt/bin
/c/WINDOWS/system32
/c/WINDOWS
/c/WINDOWS/System32/Wbem
/c/WINDOWS/System32/WindowsPowerShell/v1.0
/c/WINDOWS/System32/OpenSSH
/c/Program Files (x86)/GnuPG/bin
/c/Program Files/TortoiseSVN/bin
/c/Program Files/Rancher Desktop/resources/resources/win32/bin
/c/Program Files/Rancher Desktop/resources/resources/linux/bin
/cmd
/c/Users/hohwille/scoop/apps/python/current/Scripts
/c/Users/hohwille/scoop/apps/python/current
/c/Users/hohwille/scoop/shims
/c/Users/hohwille/scripts
/d/projects/_ide/bin
/usr/bin/vendor_perl
/usr/bin/core_perl

$ ide
IDE environment variables have been set for /d/projects/IDEasy in workspace main

$ echo -e ${PATH//:/\\n/}
/d/projects/IDEasy/software/node
/d/projects/IDEasy/software/java/bin
/d/projects/IDEasy/software/mvn/bin
/d/projects/IDEasy/software/tomcat/bin
/d/projects/IDEasy/software/intellij/bin
/d/projects/IDEasy/software/npm/bin
/d/projects/IDEasy/software/aws
/d/projects/IDEasy/software/eclipse
/c/Users/hohwille/bin
/c/Program Files/Git/usr/local/bin
/c/Program Files/Git/usr/bin
/c/Program Files/Git/usr/bin
/c/Program Files/Git/opt/bin
/c/WINDOWS/system32
/c/WINDOWS
/c/WINDOWS/System32/Wbem
/c/WINDOWS/System32/WindowsPowerShell/v1.0
/c/WINDOWS/System32/OpenSSH
/c/Program Files (x86)/GnuPG/bin
/c/Program Files/TortoiseSVN/bin
/c/Program Files/Rancher Desktop/resources/resources/win32/bin
/c/Program Files/Rancher Desktop/resources/resources/linux/bin
/c/Program Files/Git/cmd
/c/Users/hohwille/scoop/apps/python/current/Scripts
/c/Users/hohwille/scoop/apps/python/current
/c/Users/hohwille/scoop/shims
/c/Users/hohwille/scripts
/c/Program Files/Git/usr/bin/vendor_perl
/c/Program Files/Git/usr/bin/core_perl
```

Changes in the PATH:
* 8 new entries to tools of the project inserted at the beginning what is exactly expected and desired.
* 4 linux entries lost from the original PATH (from the second entry on)
* Entry `/d/projects/_ide/bin` lost from original PATH (major error)
* Entry `/cmd` replaced with `/c/Program Files/Git/cmd`? What is going on here?
* 4 git entries added to the new PATH. Where do they come from. Might be intended as we want to find `bash` on the PATH, but could be an internal feature not exposed via `ideasy env`. Why is `/c/Program Files/Git/usr/bin` duplicated?

### Steps to reproduce (bug) / Use Case of feature request (enhancement)

1. see above. You can also just run `ideasy env` so you do not break your current `PATH` to reproduce.

### Related/Dependent Issues

#227 

### Comments/Hints:

Bug is surely to be located in `SystemPath`. It would be good to add some trace-logging here to log the old and the new path.

### Affected version:

* OS: Windows
* Shell: Bash
* IDEasy: 2024.07.003-alpha

**Comment by hohwille** [comment]
Most probably I just fixed this bug since I made it occur in our tests now:
https://github.com/devonfw/IDEasy/pull/510/commits/0935186f888fc28c5b05d08dce504717bb490b18

**Comment by alfeilex** [comment]
The last point is caused by the output of the PATH variable in git bash. If you run `echo $PATH` in the git bash, you will see that `/mingw64/bin:/usr/local/bin:/usr/bin:/bin:` is included in the path. I don't know yet why there are duplicates

**Comment by alfeilex** [comment]
As discussed in the meeting, the reason for `/cmd` -> `/c/Program Files/Git/cmd`  this is likely beacuse %CD% was present in the system path for cmd (`%CD%/cmd` or something like this) and resolved to Git path. Unfortunately, I could not reproduce this behavior by putting `%CD%/cmd` as system variable. The variable is not resolved after `ide env` has been run.

@hohwille Could you please test the case once more with the latest SNAPSHOT? If everything is right, the issue can be closed.

**Comment by hohwille** [comment]
So for the record, I can still reproduce the issue but noticed that I do have this in my SYSTEM PATH (not USER PATH):
![image](https://github.com/user-attachments/assets/6c087048-e3b8-46c4-b4aa-b01b4e33b73e)

It is not that I have created this entry so it may actually come from git installation.
However, for me it does not make any sense if `C:\Progam Files\Git\cmd` is on my path, why it becomes just `/cmd` in git-bash and why our IDEasy magically can repair it then?
To me this turns out to be Windows + Git-Bash black magic and not a bug of IDEasy.

**Comment by hohwille** [comment]
> 4 linux entries lost from the original PATH (from the second entry on)

did you debug what is actually happening? Did you add trace logging as suggested?

The only logical explanation for this is that git-bash takes the System environment `PATH` and automatically adds these entries (`/usr/local/bin`, etc.) but does not export this. Then IDEasy gets started as a new process and only sees the System environment `PATH` but not these entries added by git `bash`. Therefore the `PATH` variable is computed and printed without these entries and the wrapper script sourced from the alias is then overwriting the `PATH` and loosing these entries.

Still the question is, why does `devonfw-ide` not show these "buggy effects"?
```
$ echo -e ${PATH//:/\\n/}
/c/Users/hohwille/bin
//usr/local/bin
//usr/bin
//bin
//opt/bin
//c/WINDOWS/system32
//c/WINDOWS
//c/WINDOWS/System32/Wbem
//c/WINDOWS/System32/WindowsPowerShell/v1.0
//c/WINDOWS/System32/OpenSSH
//c/Program Files (x86)/GnuPG/bin
//c/Program Files/TortoiseSVN/bin
//c/Program Files/Rancher Desktop/resources/resources/win32/bin
//c/Program Files/Rancher Desktop/resources/resources/linux/bin
//cmd
//c/Users/hohwille/scoop/apps/python/current/Scripts
//c/Users/hohwille/scoop/apps/python/current
//c/Users/hohwille/scoop/shims
//c/Users/hohwille/scripts
//d/projects/_ide/bin
//usr/bin/vendor_perl
//usr/bin/core_perl

$ devon
devonfw-ide environment variables have been set for /d/projects/IDEasy in workspace main

$ echo -e ${PATH//:/\\n/}
/d/projects/IDEasy/software/tomcat/bin
//d/projects/IDEasy/software/npm/bin
//d/projects/IDEasy/software/node
//d/projects/IDEasy/software/mvn/bin
//d/projects/IDEasy/software/jmc
//d/projects/IDEasy/software/java/bin
//d/projects/IDEasy/software/intellij/bin
//d/projects/IDEasy/software/eclipse
//d/projects/IDEasy/software/aws
//c/Users/hohwille/bin
//usr/local/bin
//usr/bin
//bin
//opt/bin
//c/WINDOWS/system32
//c/WINDOWS
//c/WINDOWS/System32/Wbem
//c/WINDOWS/System32/WindowsPowerShell/v1.0
//c/WINDOWS/System32/OpenSSH
//c/Program Files (x86)/GnuPG/bin
//c/Program Files/TortoiseSVN/bin
//c/Program Files/Rancher Desktop/resources/resources/win32/bin
//c/Program Files/Rancher Desktop/resources/resources/linux/bin
//cmd
//c/Users/hohwille/scoop/apps/python/current/Scripts
//c/Users/hohwille/scoop/apps/python/current
//c/Users/hohwille/scoop/shims
//c/Users/hohwille/scripts
//d/projects/_ide/bin
//usr/bin/vendor_perl
//usr/bin/core_perl
```

**Comment by alfeilex** [comment]
> The only logical explanation for this is that git-bash takes the System environment `PATH` and automatically adds these entries (`/usr/local/bin`, etc.) but does not export this. Then IDEasy gets started as a new process and only sees the System environment `PATH` but not these entries added by git `bash`. Therefore the `PATH` variable is computed and printed without these entries and the wrapper script sourced from the alias is then overwriting the `PATH` and loosing these entries.

Through further debugging, I discovered that in addition to the `PATH` input
https://github.com/devonfw/IDEasy/blob/68406b618409f2cc316bd26552415361217ce2cd/cli/src/main/java/com/devonfw/tools/ide/common/SystemPath.java#L53 
there is also an `ORIGINAL_PATH` key in `theCaseInsensitiveEnvironment` Treemap in `java/lang/ProcessEnvironment.java`

![image](https://github.com/user-attachments/assets/c691242b-8a2e-4ed9-95ec-49d8674300fc)

In my view `ORIGINAL_PATH` contains only the entries that are actually set in the system and user environment variables while `PATH` may also include inherited paths from the parent process (https://www.baeldung.com/java-system-get-property-vs-system-getenv)

After using `ORIGINAL_PATH`, the `PATH` is set correctly  after running `ide env`. It starts with the software paths of the ide and is followed by system and user environment variables without GitHub related entries.

**Comment by hohwille** [comment]
@alfeilex thanks for further analysis.
> After using ORIGINAL_PATH, the PATH is set correctly after running ide env. It starts with the software paths of the ide and is followed by system and user environment variables without GitHub related entries.

Did you read and understand my comments above? Are you saying that the entries like `/usr/bin` are then still present?
IMHO that is the major issue left.
The issue with this `/cmd` vs. `/c/Program Files/Git/cmd` is confusing but in the end not really relevant to me - `/cmd` is an invalid `PATH` entry and if we somehow magically "repair" this without understanding why, I would not call this a bug.
But if we remove entries like `/bin` or `/usr/bin`, etc. this is still a bug.
BTW: The fix preventing `IDE_ROOT/_ide/bin` being removed is already merged.

**Comment by alfeilex** [comment]
> Did you read and understand my comments above? Are you saying that the entries like `/usr/bin` are then still present?

Yes, I have understood the comments and I agree with you. Further entries like `/usr/bin` are not present if you use the "ORIGINAL_PATH" value. 

> The issue with this `/cmd` vs. `/c/Program Files/Git/cmd` is confusing but in the end not really relevant to me - `/cmd` is an invalid `PATH` entry and if we somehow magically "repair" this without understanding why, I would not call this a bug.

So my assumption is that, if you are using git-bash, you will get the output for `PATH` where some entries like `/mingw64/bin:/usr/bin:/c/Users/<user>/bin` are included by git-bash/mingw. In case that you are using git-bash to start `ide intellij` you will get the same output after running `ide env`, but with the addition of absolute paths added by mingw and that is the reason that the PATH changes the relative paths like `/mingw64/bin` to `C:\Program Files\Git\mingw64/bin`. (see here https://github.com/moby/moby/issues/24029#issuecomment-250412919) 

> 4 linux entries lost from the original PATH (from the second entry on)

Regarding the four Linux entries being lost from the original PATH (from the second entry onwards), the entries are not lost but converted. In devon, the paths are not converted but also included.

Oberservation:
I tried removing all system and user variables except for `C:\projects\_ide\bin`. Here are the different outputs for `PATH` in Git-Bash:

**Before running `ide` in git-bash**
```
$ echo -e ${PATH//:/\\n/}
/c/Users/alfeil/bin
//mingw64/bin
//usr/local/bin
//usr/bin
//bin
//mingw64/bin
//usr/bin
//c/Users/alfeil/bin
//c/projects/_ide/bin
//usr/bin/vendor_perl
//usr/bin/core_perl
```

**After running `ide` in git-bash**
```
$ echo -e ${PATH//:/\\n/}
/c/projects/dev/software/node
//c/projects/dev/software/java/bin
//c/projects/dev/software/mvn/bin
//c/projects/dev/software/intellij/bin
//c/projects/dev/software/npm/bin
//c/Users/alfeil/bin
//c/Program Files/Git/mingw64/bin
//c/Program Files/Git/usr/local/bin
//c/Program Files/Git/usr/bin
//c/Program Files/Git/usr/bin
//c/Program Files/Git/mingw64/bin
//c/Program Files/Git/usr/bin
//c/Users/alfeil/bin
//c/projects/_ide/bin
//c/Program Files/Git/usr/bin/vendor_perl
//c/Program Files/Git/usr/bin/core_perl
```

Output of **ORIGINAL_PATH** instead PATH (ide has been started in git-bash via `ide intellij`) https://github.com/devonfw/IDEasy/blob/68406b618409f2cc316bd26552415361217ce2cd/cli/src/main/java/com/devonfw/tools/ide/common/SystemPath.java#L53 :
```
C:\projects\dev\software\node;
C:\projects\dev\software\java\bin;
C:\projects\dev\software\mvn\bin;
C:\projects\dev\software\intellij\bin;
C:\projects\dev\software\npm\bin;
C:\Program Files\Git\mingw64\bin;
C:\Program Files\Git\usr\bin;
C:\Users\alfeil\bin;
C:\projects\_ide\bin
```

**Before running `ide` in cmd:**
```
C:\>echo %PATH%
C:\projects\_ide\bin;
C:\Users\alfeil\scripts; (added to run devon)
C:\Program Files\Git\bin (added to run git for ide intellij)

```
**After running `ide` in cmd:**
```
C:\devonfw\software\mvn\bin;
C:\devonfw\software\java\bin;
C:\projects\_ide\bin;
C:\Users\alfeil\scripts;
C:\Program Files\Git\bin;
```

**Output of PATH if intellij is started in cmd. ORIGINAL_PATH doesn't exist in cmd**
```
C:\projects\dev\software\node;
C:\projects\dev\software\java\bin;
C:\projects\dev\software\mvn\bin;
C:\projects\dev\software\intellij\bin;
C:\projects\dev\software\npm\bin;
C:\projects\_ide\bin;
C:\Users\alfeil\scripts;
C:\Program Files\Git\bin
```
Finally, you can see the difference between cmd and git-bash. However, we agree that the behavior is not caused by us, but rather by Git Bash itself or how it handles the PATH. 

I will continue to look into how we might be able to retrieve the env variables in Java without the side effect of mingw. Maybe it's an option to use `ORIGINAL_PATH` when git bash is used, so we have fewer extra entries or maybe there is another solution that I have not thought of yet. 

Let me know if I am still misunderstanding something.

**Comment by alfeilex** [comment]
> 4 linux entries lost from the original PATH (from the second entry on)

We have clarified that the missing entries are not removed but are converted into absolute paths by git-bash. 

> BTW: The fix preventing `IDE_ROOT/_ide/bin` being removed is already merged

Since the main bug is fixed, we can close this issue

**Comment by hohwille** [comment]
Update:
```
$ echo -e ${PATH//:/\\n}
/c/Users/hohwille/bin
/usr/local/bin
/usr/bin
/bin
/opt/bin
/c/WINDOWS/system32
/c/WINDOWS
/c/WINDOWS/System32/Wbem
/c/WINDOWS/System32/WindowsPowerShell/v1.0
/c/WINDOWS/System32/OpenSSH
/c/Program Files (x86)/GnuPG/bin
/c/Program Files/TortoiseSVN/bin
/c/Program Files/Rancher Desktop/resources/resources/win32/bin
/c/Program Files/Rancher Desktop/resources/resources/linux/bin
/cmd
/c/Users/hohwille/scoop/apps/python/current/Scripts
/c/Users/hohwille/scoop/apps/python/current
/c/Users/hohwille/scoop/shims
/c/Users/hohwille/scripts
/d/projects/_ide/bin
/usr/bin/vendor_perl
/usr/bin/core_perl

$ ide
IDE environment variables have been set for /d/projects/IDEasy in workspace main

$ echo -e ${PATH//:/\\n}
/d/projects/IDEasy/software/jmc
/d/projects/IDEasy/software/node
/d/projects/IDEasy/software/java/bin
/d/projects/IDEasy/software/mvn/bin
/d/projects/IDEasy/software/tomcat/bin
/d/projects/IDEasy/software/intellij/bin
/d/projects/IDEasy/software/npm/bin
/d/projects/IDEasy/software/aws
/d/projects/IDEasy/software/eclipse
/c/Users/hohwille/bin
/c/Program Files/Git/usr/local/bin
/c/Program Files/Git/usr/bin
/c/Program Files/Git/usr/bin
/c/Program Files/Git/opt/bin
/c/WINDOWS/system32
/c/WINDOWS
/c/WINDOWS/System32/Wbem
/c/WINDOWS/System32/WindowsPowerShell/v1.0
/c/WINDOWS/System32/OpenSSH
/c/Program Files (x86)/GnuPG/bin
/c/Program Files/TortoiseSVN/bin
/c/Program Files/Rancher Desktop/resources/resources/win32/bin
/c/Program Files/Rancher Desktop/resources/resources/linux/bin
/c/Program Files/Git/cmd
/c/Users/hohwille/scoop/apps/python/current/Scripts
/c/Users/hohwille/scoop/apps/python/current
/c/Users/hohwille/scoop/shims
/c/Users/hohwille/scripts
/d/projects/_ide/bin
/c/Program Files/Git/usr/bin/vendor_perl
/c/Program Files/Git/usr/bin/core_perl
```

So the situation has changed and the only remaining observation is that Linux paths (like `/user/local/bin`) are now changed to absolute Windows paths in MINGW style (like `/c/Program Files/Git/usr/local/bin`).
Sorry, for all the confusion but it is better to keep challenging a bug and ensure everything is really correct than closing it too early while it is still buggy.

The change from the Linux path is not what we should consider a bug:

```
$ ls /usr/local/bin/
iconv.exe*         libiconv-2.dll*  libxmlsec1-openssl.dll*  xmlcatalog.exe*  xmlsec1-config*  zlib1.dll*
libcharset-1.dll*  libxml2-2.dll*   libxslt-1.dll*           xmllint.exe*     xslt-config*
libexslt-0.dll*    libxmlsec1.dll*  xml2-config*             xmlsec1.exe*     xsltproc.exe*

$ ls "/c/Program Files/Git/usr/local/bin"
iconv.exe*         libiconv-2.dll*  libxmlsec1-openssl.dll*  xmlcatalog.exe*  xmlsec1-config*  zlib1.dll*
libcharset-1.dll*  libxml2-2.dll*   libxslt-1.dll*           xmllint.exe*     xslt-config*
libexslt-0.dll*    libxmlsec1.dll*  xml2-config*             xmlsec1.exe*     xsltproc.exe*
```

Therefore, I am closing this issue now.
